services:
  app:
    image: dev-tailwind-config-generator
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - WATCHPACK_POLLING=true
    container_name: dev-tw-app
